# Generated by Django 4.2.5 on 2024-02-06 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_response_question_user_response_delete_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
