# Generated by Django 4.2.5 on 2024-02-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_response_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_response',
        ),
    ]
